name: ar_international
description: AR International App
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  pdf: ^3.10.7
  printing: ^5.12.0

flutter:
  uses-material-design: true
