name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # লেটেস্ট ভার্সন

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # বিল্ড দ্রুত করার জন্য

      - name: Install Dependencies
        run: flutter pub get

      - name: Clean Project
        run: flutter clean # পুরনো ক্যাশে এরর দূর করতে

      - name: Build APK (Release)
        run: flutter build apk --release # এখানে বিল্ড সফল হবে

      - name: Upload APK
        uses: actions/upload-artifact@v4 # লেটেস্ট আপলোড মেথড
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
